CREATE TABLE person
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE authority
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE authority_person
(
    authority_id BIGINT NOT NULL,
    person_id    BIGINT NOT NULL,
    CONSTRAINT pk_authority_person PRIMARY KEY (authority_id, person_id)
);

ALTER TABLE authority
    ADD CONSTRAINT uc_role_name UNIQUE (name);

ALTER TABLE authority_person
    ADD CONSTRAINT fk_authority_person_on_person FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE authority_person
    ADD CONSTRAINT fk_authority_person_on_role FOREIGN KEY (authority_id) REFERENCES authority (id);